import './globals.css';
import localFont from 'next/font/local';
import { ProviderWrapper } from '@/redux/ProviderWrapper';
import Header from './Header';

const tMoney = localFont({
  src: [
    {
      path: '../assets/fonts/TmoneyRoundWindRegular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/TmoneyRoundWindExtraBold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
});

export const metadata = {
  title: '비즈 스캐너',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className={tMoney.className}>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className="flex flex-col min-h-screen">
        <ProviderWrapper>
          <Header />
          {children}
        </ProviderWrapper>
      </body>
    </html>
  );
}
